linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - structcheck # deprecated
    - varcheck # deprecated
    - deadcode # deprecated
    - nosnakecase # deprecated
    - ifshort # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/milad-ahmd/go-clean-arch

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - bin/
